codeforbtv/baby-equipment-exchange

src/api/firebase.ts
Added functions that can be imported into the login page so calls to getAuth stay in api/firebase.ts
=> Add firebase auth functions

src/app/about/About.module.css, src/app/about/page.tsx, src/app/contact/Contact.module.css, src/app/contact/page.tsx, src/app/layout.tsx, src/components/ButtonContainer.module.css, src/components/Header.tsx, src/styles/fonts.ts, src/styles/globalStyles.module.css
Resubmitting changes contained in #35 - specifically the addition of
About Page & Styles
Contact Page & Styles
Typography Font Imports for global usage via google fonts (Montserrat & Garamond) 
Additionally added content per update from @ksnielsen 10/23 specifically to the About and Contact pages to address #38
=> Wireframes v3 (resubmit)

src/api/firebase-donations.ts, src/api/firebase-images.ts, src/app/donate/page.tsx
Updated the Donation page's handleFormSubmit function to upload images to the Firebase storage and Donations to the Firestore FB.
- Added submit state to display Loader while attempting to upload donation data.
- If there are images included in the donation form, it creates a FileList containing each image file, uploads it to firebase storage, and returns an array containing the image IDs. 
- Creates a newDonation object containing all the relevant fields from the FormData, including the imageId array, and passed it to the addDonation function. 
- If successful, routes to the browse/home page. (Do we want to create a successful donation page/notification?) 
- If it fails displays a toaster notification letting user know that submission failed. 
Added metadata to imageUploads function to …
=> Handle image/donation uploads

src/api/firebase-donations.ts, src/api/firebase-events.ts, src/api/firebase-images.ts, src/api/firebase.ts, src/components/Browse.tsx, src/components/Dashboard.tsx, src/models/event.ts
Pulling in code from Bryan's repo that was forked from our repo...
=> API refactor

package-lock.json, package.json, src/api/firebase-donations.ts, src/api/firebase-events.ts, src/api/firebase-images.ts, src/api/firebase-users.ts, src/api/firebase.ts, src/api/firebaseAdmin.ts, src/app/about/About.module.css, src/app/about/page.tsx, src/app/contact/Contact.module.css, src/app/donate/page.tsx, src/app/donations/[id]/page.tsx, src/app/join/page.tsx, src/components/Browse.tsx, src/components/NewUserDialog.tsx, src/components/UserCard.tsx, src/models/event.ts, src/styles/globalStyles.css
- Creates firebaseAdmin filed for server functions formally deployed to G Cloud. 
- Update existing imports to use said server functions
- Font styling updates
=> Cloud refactor

src/api/firebase-donations.ts, src/api/firebase.ts, src/api/firebaseAdmin.ts, src/components/Dashboard.tsx, src/components/NewUserDialog.tsx, src/components/UserCard.tsx, src/components/UserManagement.tsx, src/types/post-data.ts
Adds admin functionality and allows admins to change access (custom claims) for other users. 
Refactor join page to add "Display Names" to database.
=> Admin page

src/app/login/page.tsx, src/components/ToasterNotification.tsx
=> Replace login toaster with field error highlighting

src/app/about/page.tsx
A few small corrections to the about page
=> Update about page links and fix spelling mistake

src/api/firebaseAdmin.ts
This only imports the serviceAccount and corresponding credentials if the environment mode is NOT set to "production." Production mode should use the default credentials provided by Firebase App Hosting.
=> Initialize admin app instance based on mode

apphosting.yaml
Add calendly secret and node_env for app hosting
=> Add Calendly secret, node_env

src/api/firebase-donations.ts, src/api/firebase-images.ts, src/api/firebase.ts, src/app/donate/Donate.module.css, src/app/donate/page.tsx, src/components/Browse.tsx, src/components/DonationCard.tsx, src/components/DonationForm.tsx, src/components/ExistingDonationDialog.tsx, src/components/UserCard.tsx, src/contexts/UserContext.tsx, src/models/donation.ts, src/models/image.ts, src/models/inventoryItem.ts, src/types/post-data.ts
Refactors the Donation model and associated code to improve performance and simplify firestore collections. Creates an InventoryItem model for donations that are available to be requested. 
**src/api/firebase-images.ts**
- Store images as URL strings instead of document references to improve load times. 
**src/api/firebase.ts**
- Reduce number of user claims, add function to check for 'aid-worker' claim.
**src/app/donate/page.tsx**
- Add email confirmation field, functionality
**src/components/Browse.tsx**
- Fetch all donations if admin, fetch only inventory if aid-worker. 
**src/contexts/UserContext.tsx**
- Add aid-worker claim check to User context. 
**src/models/***
- Update donation, image models, add inventory item model
=> Donation remodel

src/app/reject/[id]/page.tsx
Firebase apphosting is the best.
=> Cleanup, apphosting fix

src/components/NewDonationDialog.tsx
Ok, apphosting was kinda helpful here.
=> Resolve build errors

functions/src/index.ts, src/api/firebase-users.ts, src/api/firebase.ts, src/api/firebaseAdmin.ts, src/app/users/[id]/page.tsx, src/components/UserCard.tsx, src/components/UserManagement.tsx, src/models/user.ts, src/types/UserTypes.ts
Uses a cloud function to allow admins to enable user auth accounts, which are disabled by default.
=> Enable User functionality

functions/src/index.ts, src/api/firebase-organizations.ts, src/api/firebase.ts, src/app/join/page.tsx, src/app/users/[id]/page.tsx, src/models/user.ts, src/types/OrganizationTypes.ts, src/types/UserTypes.ts
Organization field on join form seaches existing organization, but allows user to type anything in in case org doesn't exist. User page checks if org exists and prompts admin to edit or create a new org if it does not.
=> List org names on join page

functions/src/index.ts, src/api/firebase.ts, src/app/join/page.tsx, src/app/users/[id]/page.tsx, src/models/user.ts, src/types/OrganizationTypes.ts, src/types/UserTypes.ts
Fixes issue creating new users. 
If user selects an existing organization, it's name and id is stored in the user doc in db. 
If user enters non-existant org, its name is added as a note in the user doc.
=> Create users fix

firestore.rules, functions/src/index.ts, src/api/firebase-donations.ts, src/api/firebase-users.ts, src/api/firebase.ts, src/api/firebaseAdmin.ts, src/app/join/page.tsx, src/app/users/[id]/edit/page.tsx, src/app/users/[id]/page.tsx, src/components/CustomDialog.tsx, src/components/EditUser.tsx, src/components/UserCard.tsx, src/components/UserManagement.tsx, src/models/donation.ts, src/models/user.ts, src/types/UserTypes.ts, src/types/post-data.ts
Creates route to view and edit user accounts.
=> User routes

functions/src/index.ts, src/api/firebase.ts, src/app/join/page.tsx
Prevent users from creating accounts without phone numbers. Update enable user cloud function.
=> Join updates

src/api/firebase-organizations.ts, src/components/DonationCard.tsx, src/components/DonationDetails.tsx, src/components/EditDonation.tsx
Updates tag number on category change, remove undefined tag numbers.
=> Tag updates

functions/src/index.ts, src/api/firebase-users.ts, src/api/firebase.ts, src/api/firebaseAdmin.ts, src/app/users/page.tsx, src/components/Dashboard.tsx, src/components/EditUser.tsx, src/components/NotificationCard.tsx, src/components/Notifications.tsx, src/components/UserCard.tsx, src/components/UserDetails.tsx, src/components/Users.tsx, src/email-templates/rejectUser.ts, src/models/user.ts, src/types/NotificationTypes.ts, src/types/UserTypes.ts
Fetches users from DB instead of auth users, updates the way users are displayed, and enabled accept/reject for new sign ups.
=> User updates
